### ISSUE TITLE
Unable to see in menu

### ISSUE THREAD

**Issue by tonglil** [nathan-osman/REST-Easy#30]
Hi, I am trying to get access to this extension but can't find it in the menu.

How can I build the .xpi file to try to install the latest version? I tried using [cfx](https://developer.mozilla.org/en-US/Add-ons/SDK/Tutorials/Installation) but there isn't a `package.json` file.

![screen shot 2014-12-30 at 11 53 30 pm](https://cloud.githubusercontent.com/assets/3250776/5586332/1a5a0d92-907f-11e4-813c-a197da8ad0c2.png)

**Comment by nathan-osman** [comment]
If you visit this page, you can try out version 0.3, which is currently pending review:

https://addons.mozilla.org/en-US/firefox/addon/rest-easy/versions/

**Comment by tonglil** [comment]
Thanks.
