### ISSUE TITLE
Still Unable to see in menu ?

### ISSUE THREAD

**Issue by g88704** [nathan-osman/REST-Easy#31]
Hello,

I still can't see the Rest-Easy addon in the Firefox menu. I already read the corresponding and closed issue but I can't install the latest version 0.3.0. I use Firefox 35 and the only version I can install is 0.2.8.

What can I do to reactivate your great add-on?

Thanks and Regards
Michael

**Comment by nathan-osman** [comment]
Thanks for reminding me. Looks like I'll have to resubmit it to AMO since it appears that the new version wasn't accepted.

**Comment by g88704** [comment]
any news on this? Version 0.2.8 is the only one I can install from the Firefox repo.

Thanks and Regards

**Comment by nathan-osman** [comment]
I've submitted the version again. All I can do at this point is wait.

**Comment by tpo** [comment]
Hi there,

FF 31.4.0 (in Debian's flavour - aka Iceweasel) here. I tried to install v 0.2.9a mentioned here: https://github.com/nathan-osman/REST-Easy/issues/30, v0.2.8, v0.2.7 ...

But none of them makes the menu entry appear. I even restarted. No success.

Is v 0.3.0 available anywhere, so I could test that as well?

?

**Comment by nathan-osman** [comment]
I've uploaded it here: http://files.quickmediasolutions.com/xpi/REST-Easy-0.3.0.xpi

**Comment by tpo** [comment]
Thanks Nathan

Now there's an Icon for REST-Easy in the toolbar, so I am able to access it. There's still no entry in the Tools->Web Developer menu.

However since REST-Easy is a tool that I won't be using every day, I'd prefer it to be only available/hidden in the Tools->Web Developer menu instead of figuring as an additional icon in the allready crowded toolbar.

**Comment by nathan-osman** [comment]
Please feel free to open a new bug to add an item to the Web Developer toolbar if you would like to see this implemented.

That being said, the toolbar button doesn't need to be _visible_ in the toolbar. The button at the far right of the toolbar opens a graphical menu and if you click "customize", you can drag the button from the toolbar to the menu:

![](http://i.stack.imgur.com/Egjgy.png)

**Comment by tpo** [comment]
Perfect, thanks!

**Comment by hackel** [comment]
I got the toolbar icon when I installed 0.2.8, but when I upgraded to 0.3.1 it disappeared.  I also installed the latest master, and it's still missing.  FF 38.0a2

**Comment by SystemZ** [comment]
0.2.8 version available from browser doesn't have any icon to launch :/ I think it's very frustrating for those who doesn't use google :)
Provided version from this link works ok http://files.quickmediasolutions.com/xpi/REST-Easy-0.3.0.xpi

**Comment by nathan-osman** [comment]
I'm frustrated too. I submitted the update to Mozilla well over two months ago and it still hasn't been approved.

**Comment by christophlingg** [comment]
thanks for providing the link for version 0.3.0. now i can use this great extension!

**Comment by nathan-osman** [comment]
And finally the update is approved and is available for download from AMO. This issue can now officially be closed.
