### ISSUE TITLE
Double-click to edit value & name

### ISSUE THREAD

**Issue by kenrick95** [nathan-osman/REST-Easy#32]
I've been using this extension for some time and would like to request this feature: when one double clicks the table cell (value or name), the value become editable. Current workaround is to delete the entry (row) and add it back again. The approach of double-click editing has been widely accepted in many applications, e.g. [Postman](http://getpostman.com/), and phpMyAdmin.

I've tried to write the feature, but unfortunately I'm not familiar with Ember.js (and I've gone ahead to write it but still no luck to produce what I want). Probably I need some time to learn using Ember.js before writing the feature myself. In the meantime, I'd like to share this idea to see if anyone is interested.

**Comment by set-killer** [comment]
I vote up for this. It will be really usefull.
