### ISSUE TITLE
Make compatible with GitHub Extension Installer

### ISSUE THREAD

**Issue by hackel** [nathan-osman/REST-Easy#34]
Can this be made compatible with the GitHub Extension Installer (https://github.com/diegocr/GitHubExtIns)?  Not sure why this doesn't work, since your install.rdf is in the root, but there must be some incompatibility.

**Comment by nathan-osman** [comment]
I get an error in the Browser Console when I try to install the add-on:

    NS_ERROR_FILE_CORRUPTED: Component returned failure code: 0x8052000b (NS_ERROR_FILE_CORRUPTED) [nsIZipReader.open]

This doesn't look like an error with REST Easy, but rather an error with GitHubExtInst. (The error occurs on [this line](https://github.com/diegocr/GitHubExtIns/blob/master/bootstrap.js#L109) in particular.) It might be worth filing an issue with their project to let them know that the extension isn't working correctly.

**Comment by nathan-osman** [comment]
I re-tested this and it appears to be working now.
