### ISSUE TITLE
differentiate headers and parameters tabs

### ISSUE THREAD

**Issue by cotto** [nathan-osman/REST-Easy#39]
I'm constantly editing a request's parameters when I mean to edit its headers.  Technically this could be blamed on user error but it doesn't help that the UI makes the two tabs look nearly identical.  A thicker line around tabs or a larger font for the active tab would make the state of the UI more obvious.

edit: I'm on 0.2.8.  If the screenshots in the readme reflect 0.3.x, then that looks like it'll help.

**Comment by nathan-osman** [comment]
Yes, the interface has changed quite a bit in 0.3.x including the arrangement of the header and request parameter tables. Unfortunately, I'm still waiting for Mozilla to approve the new version.

**Comment by nathan-osman** [comment]
The new version is now available for installation.
