### ISSUE TITLE
https calls don't work

### ISSUE THREAD

**Issue by mirkoperillo** [nathan-osman/REST-Easy#46]
I tried to invoke a GET call on a service in https and nothing appears. It seems that addon doesn't do anything. (response code is 0 without headers of response).

the same call works correctly on RESTClient addon

**Comment by InfernoZeus** [comment]
This seems to be caused by REST-Easy appending `http://` to the start of the requested URL, e.g. `https://api.github.com/` becomes `http://https://api.github.com/`.

**Comment by InfernoZeus** [comment]
Specifically [this line](https://github.com/nathan-osman/REST-Easy/blob/master/content/js/application.js#L131) is the problem. It should probably also check that it doesn't start with `https`.
