### ISSUE TITLE
Storage for commonly issued requests

### ISSUE THREAD

**Issue by nathan-osman** [nathan-osman/REST-Easy#8]
Currently, all requests must be entered from scratch - there is no way to have requests preserved between sessions. It would be awesome if the requests could be named and stored for later retrieval.

**Comment by set-killer** [comment]
Hello,
I've tried to create this feature but i couldn't complete it.
However, I created the "Save" option in this pull request: https://github.com/nathan-osman/REST-Easy/pull/37  (don't comment the ugly interface, its my best).

I am not familiar with EmberJS so i cannot create the dropdown with the saved requests (load) and the delete option, but i've put some code there for example how to proceed with the IndexedDB (this code is not fully functional!).

PS: Firefox have restrictions for the addons on window.localStorage, therefore we have to use IndexedDB.

**Comment by nathan-osman** [comment]
Thanks! I've merged it in and I'll take care of integrating the storage with Ember.

**Comment by set-killer** [comment]
Thank you! This feature is vary useful in the everyday work.

**Comment by palohan** [comment]
hi, in my clone of your repo I changed objectStore.<b>add</b> to objectStore.<b>put</b>, as this allows you to update your saved request.

from <a href="https://developer.mozilla.org/en-US/docs/Web/API/IDBObjectStore/put">MDN</a>: <i> The put method is an update or insert method. See the IDBObjectStore.add method for an insert only method.</i>

**Comment by mirkoperillo** [comment]
I think this issue can be closed
